CREATE TABLE TBL_ALUNOS_RM97898(
    ID_ALUNO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50),
    TURMA VARCHAR(20),
    RM INTEGER);
    
SELECT * FROM TBL_ALUNOS_RM97898;

DROP TABLE TBL_ALUNOS_RM97898;
